### ISSUE TITLE
Feature request: Fans with more than 3 speeds

### ISSUE THREAD

**Issue by rohankapoorcom** [finity69x2/fan-percent-button-row#3]
I have a couple of 4 speed fans (mapped to 25, 50, 75, 100%), it would be great to get another button on the card to control that last speed.

**Comment by finity69x2** [comment]
I've been asked a few times for this and I've always been reluctant to make more buttons because I've been asked to create the ability to have up to 10 buttons!

I might be able to add another button (or maybe better to create another 4 speed button plugin) but I can see this getting out of hand and at a certain point it's just becomes easier for people to use the other "button" type plugins offered by others for Lovelace.

I'll think about it but no promises. :)
