### ISSUE TITLE
state not showing on buttons

### ISSUE THREAD

**Issue by ctrl50** [finity69x2/fan-percent-button-row#7]
hey,  me again. lol

So im using the ifan03s with the https://github.com/AlexxIT/SonoffLAN integration which is actually really nice, So the fans are on stock firmware- Your other fan control has been working fine. So all I did wsa install the percent row, and change the custom:fan-percent-button-row line in my code.

The fans do work with the percent row, as seen in my .gif.. just isnt showing the state color on the buttons.
edit: off button does not work.

So not sure where to begin here. Dont know if its on my side or the integration.

![Peek 2021-05-04 03-57](https://user-images.githubusercontent.com/51256504/116994589-c1663800-ac8d-11eb-9831-752c8299721c.gif)

**Comment by finity69x2** [comment]
I think your fan is still using the speeds (which are being deprecated but aren't yet) but the fan percent buttons are using the set_percent service call and then expecting a state in percent returned from the actual fan entity.

The service call to set the percent still works because I think the percents are (for now) being automatically converted to speeds in the background for use with your fan.

but the percents aren't being converted back to speeds for the states. And the buttons only use percent values to determine the active/colors for the buttons.

and that theory is reinforced by the log entry showing that you are getting as warning that set_speed is deprecated.

I don't use the built-in firmware for the iFan03 so there's no way for me to really test my theory. But if you look at the fan attributes you should see one called "percentage:". If not that is the issue.

**Comment by ctrl50** [comment]
I think your right. I'll look into it more. But for now I think I'll close this and see how it all plays out in home assistant. 

Thanks.

**Comment by hooverds54** [comment]
seem to have a similiar problem in that the "High" "Medium" and "Low" button never show a change in state but using the Tuya Smart App I am able to see that the fan settings are correctly being set.  However setting the speed does not actually turn on the fan.  Additionally the Off button does nothing.
